spring.application.name=verifica_boleto

# Configurações do Banco de Dados (O Render vai preencher isso)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Integrações com os Microserviços
gemini.api.key=${GEMINI_API_KEY}
ml.service.url=${ML_SERVICE_URL}

# Upload de arquivos (PDFs dos boletos)
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Perfil ativo padrão
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}